### ISSUE TITLE
High ping

### ISSUE THREAD

**Issue by itsrec0very** [plasmoapp/pv-addon-lavaplayer-lib#16]
Hi all, ping on the server is increasing, looks like a ddos. In the console the following error:
![ping](https://github.com/plasmoapp/pv-addon-lavaplayer-lib/assets/104253700/4cfed8bd-a2e2-4c98-81aa-c827f58993c2)
Could it be because of the addon or it has nothing to do with it?

**Comment by Apehum** [comment]
I think this error message is consequence of the possible ddos, not the cause. The error message just means that lavaplayer can’t connect to the google servers because of some sort of connection issues
